docs_dir: handbook

site_name: OASCI Handbook
copyright: Copyright &copy; 2023, OASCI
site_author: OASCI

# Github
repo_name: oasci/handbook
repo_url: https://github.com/oasci/handbook

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  language: en
  palette:
    primary: indigo
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - navigation.footer

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Options need to be indented twice for some reason?
plugins:
  - search
  - git-committers:
      repository: oasci/handbook
      branch: main
      docs_path: handbook
  - material-plausible

extra:
  generator: false
  analytics:
    provider: plausible
    domain: handbook.oasci.org

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: false
      auto_title: false
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      url_download: true
